### ISSUE TITLE
Date sorting

### ISSUE THREAD

**Issue by projct1** [BernhardtD/vue-sorted-table#25] opened 2021-04-16 17:23 UTC
Hi!
This plugin cant sort dates?
https://skr.sh/s7bnHC86cT0
All dates only in bottom all time https://skr.sh/s7bb7nBuEny

**Comment by BernhardtD** [comment] 2021-04-20 07:06
Duplicate of #17 . Closed.

**Closed as completed by BernhardtD** 2021-04-20 07:06 UTC

**Comment by projct1** [comment] 2021-04-20 12:48
Thanks. But i moved to https://xaksis.github.io/vue-good-table/ and happy) Totally no pain now)
